# Generated by Django 3.2 on 2021-04-17 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яё\\s]+|[a-z\\s]+)$')], verbose_name='first_name'),
        ),
    ]
