# Generated by Django 3.2 on 2021-04-17 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(regex='\\w[\\w\\.-]*@\\w[\\w\\.-]+\\.\\w+')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')], verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яё\\s]+|[a-z\\s]+)$')], verbose_name='last_name'),
        ),
    ]
