# Generated by Django 3.2 on 2021-04-17 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210417_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')], verbose_name='last_name'),
        ),
    ]
