# Generated by Django 3.2 on 2021-04-18 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^ (^[0-9]{5}(?:-[0-9]{4})?$ | ^ $)')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
