# Generated by Django 3.2 on 2021-04-18 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210418_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='Example: Pushkinska 13', max_length=250, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(help_text='Example: Kharkov, Kyiv', max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(help_text='Example: example@gmail.com', max_length=254, validators=[django.core.validators.RegexValidator(regex='\\w[\\w\\.-]*@\\w[\\w\\.-]+\\.\\w+')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(help_text='Example: Ivan, Dmytro, Vasya', max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')], verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(help_text='Example: Miroshnichenko, Yarosh, Galagan', max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')], verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Example: +380663846078 / 0663846078', max_length=20, validators=[django.core.validators.RegexValidator(regex='^ (^[0-9]{5}(?:-[0-9]{4})?$ | ^ $)')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(help_text='Example: 20501, 30512', max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
