# Generated by Django 3.2 on 2021-04-18 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210418_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(help_text='Example: Ivan, Dmytro, Vasya', max_length=50, validators=[django.core.validators.RegexValidator(regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+|[0-9]+)$')], verbose_name='first_name'),
        ),
    ]
