# Generated by Django 3.2 on 2021-05-06 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20210418_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='Example: Pushkinska 13', max_length=250, validators=[django.core.validators.RegexValidator(message='В адресе не должно быть *,\\//', regex='^[0-9a-zA-Zа-яА-Яё. ]+$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(help_text='Example: Kharkov, Kyiv', max_length=50, validators=[django.core.validators.RegexValidator(message='Название города должно состоять из букв', regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(help_text='Example: Ivan, Dmytro, Vasya', max_length=50, validators=[django.core.validators.RegexValidator(message='Имя должно состоять из букв', regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')], verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(help_text='Example: Miroshnichenko, Yarosh, Galagan', max_length=50, validators=[django.core.validators.RegexValidator(message='Фамилия должна состоять из букв', regex='^([а-яА-Яё\\s]+|[a-zA-Z\\s]+)$')], verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Example: +380663846078 / 0663846078', max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен состоять из цыфр', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(help_text='Example: 20501, 30512', max_length=5, validators=[django.core.validators.RegexValidator(message='Почтовый индекс должен состоять из 5 цыфр', regex='^(^[0-9]{5}(?:-[0-9]{4})?$|^$)')]),
        ),
    ]
